sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  alioss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: ${OSS_ACCESS_KEY_ID:}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET:}
    bucket-name: sky-take-out-njx-2026-2-24

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0

  wechat:
    appid: wx5204c63d7e0821e4
    secret: 700c5efe1fecb3582cf020facfea1995

